schema {
    query: Query
    mutation: Mutation
}

type Query {
    patientAppointments(patientId: ID!): [Consulta]
    futureAppointments(patientId: ID!): [Consulta]
    patientHistory(patientId: ID!): [Historico]
}

type Mutation {
    createAppointment(agendamentoCreateDTO: AgendamentoCreateInput!): Consulta
    updateAppointment(agendamentoUpdateDTO: AgendamentoUpdateInput!): Consulta
    deleteAppointment(id: ID!): Boolean
}

input AgendamentoCreateInput {
    pacienteId: ID!
    medicoId: ID!
    dataConsulta: String!
    observacao: String
    status: String!
}

input AgendamentoUpdateInput {
    id: ID!
    dataConsulta: String
    observacao: String
    status: String
}

type Consulta {
    id: ID!
    status: String!
    observacao: String
    dataConsulta: String!
    paciente: Usuario!
    medico: Usuario!
}

type Historico {
    id: ID!
    diagnostico: String
    tratamento: String
    dataAtualizacao: String!
    paciente: Usuario!
    medico: Usuario!
}

type Usuario {
    id: ID!
    nome: String!
    cpf: String!
    login: String
    email: String
    tipoUsuario: TipoUsuario!
}

enum TipoUsuario{
    MEDICO
    ENFERMEIRO
    PACIENTE
}
