schema {
    query: Query
}

type Query {
    patientAppointments(patientId: ID!): [Consulta]
    futureAppointments(patientId: ID!): [Consulta]
    patientHistory(patientId: ID!): [Historic]
}

type Consulta {
    id: ID!
    status: String!
    observacao: String
    dataConsulta: String!
    paciente: Usuario!
    medico: Usuario!
}

type Historico {
    id: ID!
    diagnostico: String
    tratamento: String
    dataAtualizacao: String!
    paciente: Usuario!
    medico: Usuario!
}

type Usuario {
    id: ID!
    nome: String!
    cpf: String!
    login: String
    email: String
    tipoUsuario: TipoUsuario!
}

enum TipoUsuario{
    MEDICO
    ENFERMEIRO
    PACIENTE
}